In [4]:
import pandas as pd

all = pd.read_csv("../groundtruth/frame/all.csv")
seq = pd.read_csv("../groundtruth/sequence/15fps.csv")
note= pd.read_csv("../noted/5.csv")

all

,id,classe,frame,end_seq,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,...,AU10_r,AU12_r,AU14_r,AU15_r,AU17_r,AU20_r,AU23_r,AU25_r,AU26_r,AU45_r
0,5,1,202,213,1.31,0.46,1.62,0.0,0.11,1.67,...,1.19,1.19,0.64,0.17,0.17,0.00,0.00,1.02,0.81,0.82
1,5,1,203,213,1.23,0.25,1.60,0.0,0.07,1.84,...,1.04,1.19,0.63,0.26,0.41,0.00,0.00,0.72,0.99,0.78
2,5,1,204,213,1.15,0.37,1.58,0.0,0.17,2.14,...,0.85,1.22,0.70,0.27,0.67,0.06,0.03,0.99,1.02,0.71
3,5,1,205,213,0.81,0.25,1.53,0.0,0.29,2.38,...,0.65,1.31,0.59,0.10,0.51,0.06,0.03,1.38,1.10,0.52
4,5,1,206,213,0.61,0.22,1.51,0.0,0.42,2.41,...,0.54,1.40,0.40,0.01,0.28,0.06,0.03,1.82,1.09,0.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38586,20,4,16096,16100,0.00,0.00,0.34,0.0,1.02,1.24,...,0.76,0.02,0.64,0.52,0.57,0.02,0.98,0.23,1.34,0.00
38587,20,4,16097,16100,0.00,0.00,0.45,0.0,1.08,1.23,...,0.79,0.00,0.48,0.49,0.78,0.02,1.01,0.42,1.53,0.00
38588,20,4,16098,16100,0.15,0.00,0.68,0.0,1.09,0.89,...,0.92,0.00,0.24,0.48,1.45,0.29,0.93,0.72,1.60,0.00
38589,20,4,16099,16100,0.15,0.00,0.76,0.0,1.16,0.51,...,0.97,0.28,0.21,0.62,1.59,0.47,0.70,1.51,1.09,0.00
38590,20,4,16100,16100,0.15,0.00,0.53,0.0,1.12,0.18,...,1.11,0.66,0.59,0.69,1.46,0.47,0.35,2.36,0.56,0.00

In [5]:
seq

,id,classe,inizio,fine,min_AU01_r,max_AU01_r,mean_AU01_r,stdev_AU01_r,skew_AU01_r,kurt_AU01_r,...,mean_AU26_r,stdev_AU26_r,skew_AU26_r,kurt_AU26_r,min_AU45_r,max_AU45_r,mean_AU45_r,stdev_AU45_r,skew_AU45_r,kurt_AU45_r
0,5,2,236,250,0.05,1.43,0.7620,0.5264,-0.1025,-1.6619,...,1.0307,0.6754,0.0876,-1.3331,0.0,2.03,0.7227,0.7096,0.8295,-0.7743
1,5,2,237,251,0.11,1.63,0.8673,0.5318,-0.2241,-1.4884,...,1.0900,0.6538,-0.1124,-1.1819,0.0,2.03,0.7173,0.7150,0.8112,-0.7868
2,5,2,238,252,0.13,1.94,0.9893,0.5550,-0.1698,-1.0825,...,1.1480,0.6302,-0.3279,-0.9087,0.0,2.03,0.7067,0.7251,0.7856,-0.8137
3,5,2,239,253,0.20,2.61,1.1547,0.6431,0.4333,0.0148,...,1.2220,0.5708,-0.4846,-0.3733,0.0,2.03,0.7047,0.7266,0.7850,-0.8184
4,5,2,240,254,0.29,3.27,1.3593,0.7895,0.9629,0.6381,...,1.3167,0.4738,-0.3738,-0.1794,0.0,2.03,0.7167,0.7193,0.7752,-0.7981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30569,20,4,16081,16095,0.00,2.77,1.3673,1.1474,-0.0309,-1.6705,...,0.6693,0.4805,0.1927,-1.1877,0.0,0.01,0.0020,0.0041,1.5000,0.2500
30570,20,4,16082,16096,0.00,2.77,1.3180,1.1914,0.0001,-1.7403,...,0.7587,0.4716,0.0320,-1.3026,0.0,0.01,0.0013,0.0035,2.1573,2.6538
30571,20,4,16083,16097,0.00,2.77,1.2160,1.2366,0.1670,-1.8027,...,0.8607,0.4611,0.0106,-1.4318,0.0,0.01,0.0007,0.0026,3.4744,10.0714
30572,20,4,16084,16098,0.00,2.77,1.0620,1.2142,0.4429,-1.6220,...,0.9587,0.4509,-0.0343,-1.5336,0.0,0.00,0.0000,0.0000,0.0000,-3.0000
30573,20,4,16085,16099,0.00,2.76,0.8873,1.1370,0.7318,-1.2525,...,1.0140,0.4079,-0.0963,-1.5334,0.0,0.00,0.0000,0.0000,0.0000,-3.0000

In [6]:
note

     id  classe  inizio   fine
0     5       1     202    213
1     5       4     223    235
2     5       2     236    259
3     5       3     270    295
4     5       5     298    331
..   ..     ...     ...    ...
152   5       0   17300  17534
153   5       0   17570  17628
154   5       0   17660  17785
155   5       1   18000  18067
156   5       0   18250  18305

[157 rows x 4 columns]